project4/basic_app/urls.py
from django.urls import path
from . import views

app_name = 'basic_app'

urlpatterns = [
	path('other/',views.other,name='other'),
	path('relative/',views.relative,name='relative'),
]

project4/project4/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views

urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('basic_app/', include('basic_app.urls')),
]

project4/basic_app/models.py
from django.db import models

# Create your models here.

project4/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
	return render(request,'basic_app/index.html')

def other(request):
	return render(request,'basic_app/other.html')

def relative(request):
	return render(request,'basic_app/relative_url_templates.html')
	

project4/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
	<title>
		{% block title %}
		{% endblock %}
	</title>
</head>
<body>
	<nav class="navbar navbar-expand-lg bg-light">
		<div class="container-fluid">
			<a href="{% url 'index' %}" class="navbar-brand">Brand</a>
			<ul class="navbar-nav me-auto">
				<li class="nav-item">
					<a href="{% url 'basic_app:other' %}" class="nav-link">Other</a>
				</li>
				<li class="nav-item">
					<a href="{% url 'basic_app:relative' %}" class="nav-link">Relative URLs</a>
				</li>
				<li class="nav-item">
					<a href="{% url 'admin:index' %}" class="nav-link">Admin</a>
				</li>
			</ul>
		</div>
	</nav>

	<div class="container">
		{% block body %}
		{% endblock %}
	</div>

</body>
</html>

project4/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block title %}
Index
{% endblock %}

{% block body %}
<h1 class="display-2">Welcome to Index</h1>
{% endblock %}

project4/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block title %}
Other
{% endblock %}

{% block body %}
<h1 class="display-2">Welcome to Other</h1>
{% endblock %}

project4/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block title %}
Relative
{% endblock %}

{% block body %}
<h1 class="display-2">Welcome to Relative URL Templates</h1>
<a href="{% url 'basic_app:other' %}">Link to Other</a>
<a href="{% url 'index' %}">Link to Index</a>
<a href="{% url 'admin:index' %}">Link to Admin</a>
{% endblock %}